### ISSUE TITLE
关于NovelAI标签超市，一个改进的小提议。（关于tag的强调格式优化）

### ISSUE THREAD

**Issue by CCrous** [wfjsw/danbooru-diffusion-prompt-builder#1]
我注意到，现在网站[tag]的强调增减是通过()与[]来表达的
但是实际上，更方便的用法是
`(<tag>:<强调的数字>)`
例如
`(furry:3)`
我没有能力去编辑网站的代码，可以的话，请在网站上添加切换到这样模式的功能，谢谢

**Comment by wfjsw** [comment]
目前标签权重的存储方式是有极权重格式，比如 `((tag))` 记 `+2`，`[[[tag]]]` 记 `-3`。如果换用数字权重表示，则内部需要相应更换为无极权重，这样存在一个兼容性问题：

NovelAI 官网的旧有权重格式 (`{}` 与 `[]`) 是不支持无极权重的。 他们的强调语法中并不存在 `{tag:1.1}` 这样的说法。（他们如果支持这种格式我就不会去套括号了）

能想到的两个解决办法：
- 扔掉 NovelAI 旧格式支持
- 全部换无极权重，其中给 NovelAI 的括号数量通过 $\log_{1.05}x$ 计算并近似取整

可以看看走哪条路比较好，或者有没有其他的解决办法。

**Comment by wfjsw** [comment]
目前标签权重的存储方式是有极权重格式，比如 `((tag))` 记 `+2`，`[[[tag]]]` 记 `-3`。如果换用数字权重表示，则内部需要相应更换为无极权重，这样存在一个兼容性问题：

NovelAI 官网的旧有权重格式 (`{}` 与 `[]`) 是不支持无极权重的。 他们的强调语法中并不存在 `{tag:1.1}` 这样的说法。（他们如果支持这种格式我就不会去套括号了）

能想到的两个解决办法：
- 扔掉 NovelAI 旧格式支持
- 全部换无极权重，其中给 NovelAI 的括号数量通过 $\log_{1.05}x$ 计算并近似取整

可以看看走哪条路比较好，或者有没有其他的解决办法。

**Comment by wfjsw** [comment]
$\log_{1.05}x$ 函数图像如下图所示，其中 $x$ 为实际权重值，$y$ 为需要加的括号：
![image](https://user-images.githubusercontent.com/2220320/197317167-8e78c930-38b8-4d24-b9af-df3bfe0c6b39.png)

**Comment by CCrous** [comment]
感谢大佬，我认为应该有多个 强调格式选择，

**Comment by CCrous** [comment]
![image](https://user-images.githubusercontent.com/116413335/197328668-63d6c5e9-5027-434a-9eae-a5830e77aadc.png)
（转群友图）
大佬！
我认为，可以尝试提供多个格式的选项，比如：

`增减权重的数值` 可以分为 `加/减 0.05` 或 `加一个()或[]` 两种方式

`输出的格式` 也可以分为 `(tag:数字权重)` 或 `套括号()[]` 两种方式

总之，可以给出更多的选择就尽可能的可以满足更多人的需求
（萌新发言）

**Comment by wfjsw** [comment]
我感觉我不是很能理解你想要什么。

想要自定义权重值，还是只是想要输出权重数字代替括号？

添加自定义权重值的功能是有代价的，对于带有自定义权重的购物车无法输出准确的 NovelAI / NAIFU 后端结果（也就是大括号强调结果）。

----

> `加/减 0.05` 或 `加一个()或[]` 两种方式

`加/减 0.05` 指的是什么？ $+ 0.05$ 还是 $\times 1.05$？
这是两个完全不一样的东西，如果是前者的话，大括号支持可以直接扔了。后者与加一个括号完全相同。

> 输出的格式 也可以分为 `(tag:数字权重)` 或 `套括号()[]` 两种方式

这个可以做，而且应该比较简单。

**Comment by CCrous** [comment]
我的描述可能有点乱，抱歉啦... -w-

我作了一张图来帮助理解

![image](https://user-images.githubusercontent.com/116413335/197374079-8723c35f-aaa7-42cf-8de1-ce33abab5a9d.png)


大佬觉得能实现的可以来尝试一下，对我来说感觉代码层面会有些复杂，不用勉强...

(顺带一提，现在网页上的“导入标签”功能有些小问题，只有已有的tag才能识别出权重，例如 `((ahoge))` 可正常识别出 `ahogex1.21` ，但是其它不存在已有标签列里的标签，随便举例`(abcd)`则会出现 `abcd - (未知) ` 这是会丢失原有标签权重，这个小问题也希望更进一下，非常感谢！!）

**Comment by sudoskys** [comment]
https://github.com/sudoskys/M2NM2NBot/blob/main/utils/Converter.py
类似实现

**Comment by wfjsw** [comment]
在憋大的 不要急

**Comment by CCrous** [comment]
我是急急国王
急急急急急急
