### ISSUE TITLE
嵌入模型下载

### ISSUE THREAD

**Issue by Streamer-stars** [wfjsw/danbooru-diffusion-prompt-builder#11]
在下载超网络模型时，点击下载模型即可下载。但是在下载嵌入模型时，点击下载模型会下载配图而不是模型。是我操作有问题还是不支持下载嵌入模型呢？

**Comment by wfjsw** [comment]
将 webp 文件放置在 embeddings 目录中即可使用。

**Comment by Streamer-stars** [comment]
> 将 webp 文件放置在 embeddings 目录中即可使用。

感谢回复
