### ISSUE TITLE
嵌入模型无法使用

### ISSUE THREAD

**Issue by Streamer-stars** [wfjsw/danbooru-diffusion-prompt-builder#12]
将下载的.webp文件放入embeddings文件夹内后，在stable-diffusion-webui下无法使用。无论是输入关键词，文件名，推荐关键词等，均无效。

**Comment by wfjsw** [comment]
看一下控制台日志？

**Comment by Streamer-stars** [comment]
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: ce049c471b4a1d22f5a8fe8f527788edcf934eda
Installing requirements for Web UI
Launching Web UI with arguments: --medvram --deepdanbooru --xformers
=====================================
AUTOMATIC1111/stable-diffusion-webui
portable packed by bilibili@秋葉aaaki
本整合包完全免费
=====================================

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [6569e224] from D:\Program\novelai-webui-aki_2\models\Stable-diffusion\Anything-V3.0.ckpt
Applying xformers cross attention optimization.
Model loaded.
Error loading emedding klee-4928a5.webp:
Traceback (most recent call last):
  File "D:\Program\novelai-webui-aki_2\modules\textual_inversion\textual_inversion.py", line 134, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "D:\Program\novelai-webui-aki_2\modules\textual_inversion\textual_inversion.py", line 93, in process_file
    embed_image = Image.open(path)
  File "D:\Program\novelai-webui-aki_2\py310\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'D:\\Program\\novelai-webui-aki_2\\embeddings\\klee-4928a5.webp'

Loaded a total of 5 textual inversion embeddings.
Embeddings: bc54daf0c21fe635c41a72bf4ace1b52994bb28fe65cc74c87e69aa4b1b124bd, 4c3111ccae72ee373a72b1f625eb8da6065a6257f1f2c18bd8515600807ef514, ffd12e3b3046aa335cd134566c2b6c52b32a0888e8260980adc17130aedde667, 76da7b1f12bbd87a30006770fe446719766709bc11e5400a8b652ab7a768bfc2, 0dbf78de7cf2dad9cbef78fe9b0c5d43210ad299e4ab864200670f657f6998e1
Running on local URL:  http://127.0.0.1:7860

**Comment by Streamer-stars** [comment]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [6569e224] from D:\Program\novelai-webui-aki_2\models\Stable-diffusion\Anything-V3.0.ckpt
Applying xformers cross attention optimization.
Model loaded.
Error loading emedding klee-4928a5.webp:
Traceback (most recent call last):
  File "D:\Program\novelai-webui-aki_2\modules\textual_inversion\textual_inversion.py", line 134, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "D:\Program\novelai-webui-aki_2\modules\textual_inversion\textual_inversion.py", line 93, in process_file
    embed_image = Image.open(path)
  File "D:\Program\novelai-webui-aki_2\py310\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'D:\\Program\\novelai-webui-aki_2\\embeddings\\klee-4928a5.webp'

Loaded a total of 5 textual inversion embeddings.
Embeddings: bc54daf0c21fe635c41a72bf4ace1b52994bb28fe65cc74c87e69aa4b1b124bd, 4c3111ccae72ee373a72b1f625eb8da6065a6257f1f2c18bd8515600807ef514, ffd12e3b3046aa335cd134566c2b6c52b32a0888e8260980adc17130aedde667, 76da7b1f12bbd87a30006770fe446719766709bc11e5400a8b652ab7a768bfc2, 0dbf78de7cf2dad9cbef78fe9b0c5d43210ad299e4ab864200670f657f6998e1
Running on local URL:  http://127.0.0.1:7860

**Comment by wfjsw** [comment]
建议重新下一份

**Comment by Streamer-stars** [comment]
重新下载后还是无法使用

**Comment by wfjsw** [comment]
贴新的日志

**Comment by Streamer-stars** [comment]
![image](https://user-images.githubusercontent.com/76718993/205836568-892be9ba-aa34-435b-8267-7022c5416df1.png)

**Comment by wfjsw** [comment]
你下的是哪一个，关键词叫什么

**Comment by wfjsw** [comment]
此外，模型文件在 embeddings 文件夹的文件名叫什么

**Comment by Streamer-stars** [comment]
nahida-prompt-1ae655.webp,输入文件名，或是给的关键词的无效

**Comment by wfjsw** [comment]
奇了怪了，那我上次改了个什么

**Comment by wfjsw** [comment]
大概是好了，重新下一张试试

**Comment by Streamer-stars** [comment]
刚下载的新文件，依旧不行。
![image](https://user-images.githubusercontent.com/76718993/206441097-9131b0c8-3a96-4a02-b1e5-21bca5788d43.png)
尝试输入文件名，提供的关键词均无效。
![image](https://user-images.githubusercontent.com/76718993/206441497-8bb3adcc-be95-426c-9128-83e02eb57a1b.png)

**Comment by wfjsw** [comment]
改了忘记发布了，我的

可以再试试

**Comment by Streamer-stars** [comment]
好了
