### ISSUE TITLE
谷歌浏览器结算时没有标签显示

### ISSUE THREAD

**Issue by Chen-Luan** [wfjsw/danbooru-diffusion-prompt-builder#18]
![屏幕截图 2023-05-12 231025](https://github.com/wfjsw/danbooru-diffusion-prompt-builder/assets/62653664/c7cf5006-4a09-4426-b106-8aa7b274a63e)

**Comment by wfjsw** [comment]
看一下 F12 控制台？

**Comment by Chen-Luan** [comment]
录屏：[2023-05-13 22-50-24.zip](https://github.com/wfjsw/danbooru-diffusion-prompt-builder/files/11469928/2023-05-13.22-50-24.zip)

**Comment by wfjsw** [comment]
切到 Console 那个标签页

**Comment by Chen-Luan** [comment]
> 切到 Console 那个标签页

可恶，发现是我的广告拦截插件的问题
