### ISSUE TITLE
"嵌入模型"标签页点击下载后，下载的只是一张图片

### ISSUE THREAD

**Issue by RTX10086** [wfjsw/danbooru-diffusion-prompt-builder#2]
![image](https://user-images.githubusercontent.com/46842736/197362827-1b21a7c7-6992-4589-b7fb-0c3a9194db31.png)

点击下载模型按钮，网页只传递了一张webp图片，没有传输.pt的embedding模型

**Comment by RTX10086** [comment]
抱歉，刚刚看到文档说不支持.pt。。。

**Comment by wfjsw** [comment]
这webp可以当pt用。
