### ISSUE TITLE
是否能够以链接或者 iframe 的方式联合魔导绪论

### ISSUE THREAD

**Issue by KonghaYao** [wfjsw/danbooru-diffusion-prompt-builder#5]
您好， 我是魔导绪论的作者（https://magic-tag.netlify.app/#/）

看到您的项目非常不错，希望能够加入协助跳转到魔导绪论进行进一步编辑的功能。我正在尝试将我的应用与众多网站联合在一起，成为可以灵活组合的新形式的网站。魔导绪论支持更为庞大的词条可以使用，并且已经经过多次测试，同时借助于您的项目可以得到词条的预览，我觉得融合在一起将会非常不错。

魔导绪论提供了两种接入的方式。

1. **a 链接跳转 对应 url**，只需要在 链接的 params.tags 写入 prompt ，打开的页面就加入了词汇，并且魔导绪论支持大括号和方括号的解析。
2. 使用 iframe 像小程序一样使用魔导绪论作为您的网站的 tag 编辑器，我已经使用线程的方式实现了跨站的信息沟通，**能够双向绑定两个站点的 prompt 字符串信息**，如果您对此有兴趣，可以在 [魔导绪论](https://github.com/KonghaYao/ai-tag ) 的 demo 文件夹中找到测试的样例。

感谢您漂亮的开源网站！

江夏尧

![{{{extremely detailed CG unity 8k wallpaper}}},{{highly detailed}},{{best quality}},looking at viewer,{close up},beautiful detailed  water,beautiful detailed girl,{long black hair} s-1138862044 (1)](https://user-images.githubusercontent.com/68177907/198873647-01b29b26-a4d9-4947-b102-d2dd449728fd.png)

**Comment by wfjsw** [comment]
看不到这样做意义何在。值得一提的原因如下：
 - 貌似你您站点无法解析我站的相当一部分输出结果。我随便生成了一个串，然后您的站点 bug 掉了。它现在在抽搐、刷屏并大量占用我的 CPU。
   - 我生成的串是这样子的：`[thigh gap:bent over:0.2], [hips::0.3], crossed legs :1.05 AND kneeling :0.95`
 - 您的站点最多只支持处理 5 个括号。我小试了一下 7 个括号然后您的标签栏炸了。
 - 在站点之间进行标签转移，据我了解，我确实不认为大部分用户存在这种需求。

关于 iFrame 对接，有更多的问题：
 - 当前应用 UI 空间紧张，没有空余位置放置包括框架在内的大型控件。
 - 框架内外样式不统一，强行塞入此类控件会严重破坏用户体验。
 - 在未经用户同意的前提下嵌入不可控的跨域资源将带来严重的安全隐患，这是对站点访客的不负责任。

综上，在目前阶段我没有理由这么做。

**Comment by KonghaYao** [comment]
1. 我详细查看了您和一位同志关于括号和权重问题的描述， stable diffusion 数学模式的表达确实不适合于我的网站。
    -  因为我现在的标准是大多数平台和法典（元素法典）之间能过够通用的一个方案，很多 AI 绘图魔法师采用的是括号式的，因为大部分编辑器也是括号式的，只有少数采用了数值，详细查看魔法 qq 群里面每天那么多的大佬的 tag。。。。
    - 所以我还是忠于原文，用户看到的和复制的，是一样的。同样的，我也看到您修改为数值 base 后，元素法典部分失去了权重，这点确实遗憾。
    - 基于这些特征，我认为在不破坏所见即所得的情况下，AND 操作和 特殊的权重操作完全可以以字符串的形式，让用户自行输入，或者被解析成字符串，因为这个本来就是特例，而且数量也不应该很多（黑魔法除外，哈哈哈）。

3. 抱歉，我这边输入您的字符串，[thigh gap:bent over:0.2], [hips::0.3], crossed legs :1.05 AND kneeling :0.95]，生成了相应的解析，CPU 占用正常，如果您的设备有相关的错误，请发截图和相应的触发条件在我的项目 issues 告知我，非常感谢您的反馈。
![image](https://user-images.githubusercontent.com/68177907/198881538-bce6502c-fade-4ecd-91fb-0feecc8e2976.png)

4. 关于括号，魔导绪论支持的括号层级最大为 5 个，当然这个我将来会在设置里面添加，感谢您的反馈让魔导绪论更加完整。

5. 至于标签栏很长，twitter 上很常用的代码生成网站 carbon 也是这么做的，我也认为用户并不会认为这个是重点。

6. 我认为标签的含义体现在其图形和词汇配合，而我这边没有关于图形的资源，所以正在找可以实现大一统的对象，让整个 prompt 制作流程归于平滑。

关于 iframe 的问题：
1. 您的网站布局没有空间我可以理解，这点非常遗憾。

2. 我认为十年后的网站将会以微前端的形式实现 小程序式的嵌入，多个应用合一，实现数据流转，所以正在进行实现这点的尝试。

3. 关于 iframe 的安全性问题，您完全可以放心 Chrome 对于浏览器沙盒的处理，只要配合了相应的权限（CSP，iframe 安全属性等新型的操作），那么 iframe 也是安全的。
   -  我看到 XMind 的开源源码也是使用 iframe 通信的方式实现共享，故对此稍有了解。
   -  甚至于 Notion 也支持 网站外链，而且是任意链接，我也不清楚他们的程序员是怎么想的，哈哈哈。
   
![image](https://user-images.githubusercontent.com/68177907/198883029-ce0b8fd8-d7fc-4c3f-8501-b6717e7337d5.png)

   -  所以微前端的技术才有 iframe 一条路，我相信如果 Google 愿意支持 iframe 的话，那么将会很不错。不过那么多年 Google 也没干，估计也是朝着 Web Component 和 Web Assembly 进行了。

综上，对于您的情况我非常了解，对于无法合作我深感遗憾。

**Comment by wfjsw** [comment]
> 同样的，我也看到您修改为数值 base 后，元素法典部分失去了权重，这点确实遗憾。

这个是设计问题，最新版已经解决了，但是法典部分没有跟进。不过我确实不喜欢元素法典 xjb 给括号。

> 抱歉，我这边输入您的字符串，[thigh gap:bent over:0.2], [hips::0.3], crossed legs :1.05 AND kneeling :0.95]，生成了相应的解析，CPU 占用正常，如果您的设备有相关的错误，请发截图和相应的触发条件在我的项目 issues 告知我，非常感谢您的反馈。

复现方法如下：
1. 打开站点
2. 随便选一个 tag
3. 用上边的内容替换掉地址栏的 tag

刚才又复现了一下。

> 我认为十年后的网站将会以微前端的形式实现 小程序式的嵌入，多个应用合一，实现数据流转，所以正在进行实现这点的尝试。

恰恰相反，通过 Frame 排版网页基础功能是十年前的做法。

> 关于 iframe 的安全性问题，您完全可以放心 Chrome 对于浏览器沙盒的处理，只要配合了相应的权限（CSP，iframe 安全属性等新型的操作），那么 iframe 也是安全的。

访问跨域资源本身就是个问题，跨域代码的任意执行只是把问题变大了。

**Comment by KonghaYao** [comment]
1. 对不起，我不能复现您的电脑的错误，麻烦搞个 gif 吧

![Gallery](https://user-images.githubusercontent.com/68177907/198883749-308a6d21-6ebc-4023-aa2b-00f99b2cebb6.gif)


2. 很抱歉，SSR 也是 JSP 的类似，只不过，此时此刻正如彼时彼刻，React SSR 大火，Vue 也跟风，哎，真是的，风向易变，估计到时又要大裁员。。。

3. 跨域并不是问题， CSP 协议， CORS 协议都是解决的办法，我们不是不要跨域，而是要安全地求合作，求发展，这点其实 Google 还是懂一点的，要不直接像 Flash 一样剁掉？哈哈哈哈。

**Comment by KonghaYao** [comment]
1. 而且法典组确实是很厉害的人，他们居然能做到那么细，已经很了不起了，对于大多数人来说，并不需要买菜微积分，括号够用了。。。。
2. AI 绘图，有些人呢是炼丹师，从模型下手，他们在群里说着完全不懂的参数；而有些人呢，是魔法师，慢慢练着词汇的隐藏义。怎么说呢，前端和后端吧，两个地方了。哈哈哈。

**Comment by wfjsw** [comment]
CORS 保护的是被引人，而非引用人。它保护了被引人的资源不会未经准许被其他网页脚本使用或修改。我的 CSP 也管不来你的站，反过来也一样。

JSP 与后台直接耦合，但是 SSR 的前端站点与后台之间隔了一层接口。但是用 iFrame 引用跨域资源是直接复古了，正经的微前端也没有这么随便。

法典的问题在于成功经验不可被解释和复用，不能被解释复用的经验无法称之为经验。
> ps：如果你在里面找到了非英文分隔号、像是错拼的单词、奇怪的回车甚至任何不像是科学能解释的东西——请不用担心，那都是咒语的一部分。 
> by——元素法典制作委员会

像这种说法直接否定了它作为研究素材存在的意义。Preset 体现的是可以复用的组合，而不是一个单纯的成品展示台。

![New Project](https://user-images.githubusercontent.com/2220320/198885114-49df2d61-f752-42bd-9585-d62695b768b4.gif)

手上没有全家桶，凑合看看。

**Comment by wfjsw** [comment]
有点跑题了，先关了。
