### ISSUE TITLE
[bug]【导入标签】功能导致的显示bug

### ISSUE THREAD

**Issue by CCrous** [wfjsw/danbooru-diffusion-prompt-builder#6]
问题描述：
在点击【导入标签】并点击【保存】后，`右侧【购物车】栏` **无法正常的显示**。 **（直观的说，像是 `右侧【购物车】栏` 被 _"冻结"_ 了）** 之后的**任何操作**均不会显示在 `右侧【购物车】栏` 里，但仍会被纪录，并在点击【结算】时能正常导出所有的tag集。

希望的改进：
1. 尽快修复这个bug
2. 让【导入标签】功能可以 **添加到** 而不是 **替换掉** 掉原有的tag集（我认为这样操作会更方便一些 _（如果不会的话就算了）_ ）

麻烦了！

**Comment by wfjsw** [comment]
清空购物车也会导致类似的问题。可能是购物车结构变化导致的问题。
